index:
   path: /
   controller: App\Controller\AccueilController::index

Accueil:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: index
        permanent: true